apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scale-hpa-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: scale-hpa-sa
    namespace: default
roleRef:
  kind: Role
  name: hpa-patcher
  apiGroup: rbac.authorization.k8s.io